# Generated by Django 3.2.6 on 2021-08-10 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('duration', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('mean_pitch', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('minimum_pitch', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('maximum_pitch', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('number_of_pulses', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('number_of_periods', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('number_of_voice_breaks', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('degree_of_voice_breaks', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('jitter', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('shimmer', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('mean_autocorrelation', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('mean_noise_th_ratio', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('mean_harmonics_tr_ratio', models.DecimalField(decimal_places=6, max_digits=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plik Audio',
                'verbose_name_plural': 'Pliki Audio',
            },
        ),
    ]
